export default[
  {
    key:'0',
    title:"主页面",
    icon:'home',
    path:'/admin/home'
  },
  {
    key:'7',
    title:"用户管理",
    icon:'user',
    path:'/admin/user'
  },
  {
    key:'8',
    title:"管理员管理",
    icon:'team',
    path:'/admin/administrator'
  },
  {
    key:'1',
    title:"类别管理",
    icon:'appstore',
    path:'/admin/type/find'
  },
  {
   key:'2',
   title:'商品管理',
   icon:'shop',
   path:'/admin/shop',
   children:[
     {
       key:'2-1',
       title:"商品列表",
       path:'/admin/shop/shopList',
       icon:'ordered-list',
      },
     {
      key:'2-2',
      title:"商品添加",
      path:'/admin/shop/shopAdd',
      icon:'form',
    }
   ]
  },

  {
    key:'5',
    title:"订单管理",
    icon:'file-search',
    path:'/admin/order',
    children:[
      {
        key:'5-1',
        title:'订单列表',
        path:'/admin/order/List',
        icon:'ordered-list',
        
      },
      {
        key:'5-2',
        title:'订单审核',
        path:'/admin/order/Audit',
        icon:'edit',
      },
    ]
  },
  {
    key:'4',
    title:"数据统计",
    icon:'database',
    path:'/admin/echarts',
    children:[
      {
        key:'4-1',
        title:'饼状图',
        path:'/admin/echarts/pie',
        icon:'pie-chart',
      },
      {
        key:'4-2',
        title:'折线图',
        path:'/admin/echarts/line',
        icon:'line-chart',
      },
      {
        key:'4-3',
        title:'柱状图',
        path:'/admin/echarts/bar',
        icon:'bar-chart',
      },
    ]
  },
  {
    key:'9',
    title:"系统日志",
    icon:'setting',
    path:'/admin/log'
  },
]
